"""
Third System / AIAS framework boilerplate, v1.4.

Authored from Third_System_AIASS_v1_4.docx. Each topic has Short, Medium, and
Long versions. Short fits a one-line tagline, Medium fits a footer/about-section
on a single page, Long fits a full explanatory paragraph or page section.

Use across all Third System reports — keeps language, framing, and definitions
locked. Editing lives here, in one place.
"""

# 1. SYSTEM OVERVIEW
SYSTEM_OVERVIEW = {
    "short": (
        "Third System explains how brands compete inside AI-mediated decisions."
    ),
    "medium": (
        "The Third System describes a shift in how consumers make decisions: "
        "instead of browsing and comparing options directly, many now rely on AI "
        "systems to generate recommendations. In this environment, brands compete "
        "not only for human attention but for inclusion within AI-generated outputs. "
        "This creates a new competitive layer where visibility is determined by how "
        "AI systems interpret and surface brands."
    ),
    "long": (
        "The Third System describes a structural transformation in how markets "
        "operate. Historically, brands competed within a human-mediated environment "
        "where visibility was driven by advertising, distribution, and memory "
        "structures. Today, a growing share of decisions are mediated by AI systems "
        "that synthesize information, generate recommendations, and effectively "
        "compress the consideration set into a short list or even a single answer. "
        "In this context, brand competition shifts from influencing human "
        "perception directly to influencing how AI systems interpret and represent "
        "the category. This introduces a new layer of competition\u2014AI-mediated "
        "visibility\u2014where inclusion, prominence, and framing within AI-generated "
        "outputs become critical determinants of demand capture. The Third System "
        "provides a conceptual lens for understanding this shift and its "
        "implications for brand strategy, measurement, and growth."
    ),
}

# 2. AIAS — CORE SYSTEM
AIAS_CORE = {
    "short": "AIAS measures how brands appear in AI-generated responses.",
    "medium": (
        "AIAS (AI Availability System) is a framework designed to measure how "
        "brands show up in AI-driven environments. It captures not only whether "
        "a brand appears, but also how frequently, how consistently, and in what "
        "competitive context. This system enables organizations to observe a "
        "previously unmeasured dimension of brand performance."
    ),
    "long": (
        "The AI Availability System (AIAS) is a structured measurement framework "
        "designed to quantify brand visibility within AI-mediated environments. "
        "Unlike traditional metrics such as awareness, consideration, or market "
        "share\u2014which rely on human recall or behavior\u2014AIAS focuses on how brands "
        "are represented within machine-generated outputs that increasingly shape "
        "decision-making. The system operates by analyzing responses generated by "
        "large language models across defined prompts, extracting brand mentions, "
        "and organizing them into a set of comparable metrics. These metrics "
        "capture not only the presence of a brand, but also its relative position, "
        "stability across models, and breadth of appearance across different "
        "contexts. Over time, AIAS is designed to evolve into a multi-dimensional "
        "system that supports not only descriptive analysis, but also directional "
        "and eventually predictive insights into how AI-mediated visibility "
        "influences market outcomes."
    ),
}

# 3. CORE METRICS — PRESENCE INDEX
PRESENCE_INDEX = {
    "short": "Measures how often a brand appears.",
    "medium": (
        "The AI Presence Index is the foundational metric within AIAS. It tracks "
        "how frequently a brand is mentioned across a defined set of prompts and "
        "AI models. This metric establishes whether a brand is visible at all."
    ),
    "long": (
        "The AI Presence Index is the foundational layer of the AIAS system and "
        "represents the simplest observable measure of AI-mediated visibility. It "
        "quantifies how often a brand is mentioned across a structured set of "
        "prompts, models, and repeated runs, producing a normalized frequency "
        "score that can be compared across brands within a category. Presence "
        "answers a fundamental question: does the brand exist within the "
        "AI-generated representation of the category? Without presence, no further "
        "competitive dynamics are relevant. As such, it serves as the baseline "
        "condition for participation in AI-mediated demand capture. While simple, "
        "this metric reveals important structural effects, including the "
        "divergence between traditional awareness and AI visibility, and forms "
        "the basis for all higher-order measurements within the system."
    ),
}

# 4. CORE METRICS — SHARE OF MODEL (SOM)
SHARE_OF_MODEL = {
    "short": "Measures competitive share of visibility.",
    "medium": (
        "Share of Model (SOM) compares a brand\u2019s mentions against competitors "
        "within the same category. It shows whether a brand is leading or lagging "
        "in AI-generated recommendations. This shifts analysis from visibility to "
        "competition."
    ),
    "long": (
        "Share of Model (SOM) extends the Presence Index by introducing a "
        "competitive dimension to AI-mediated visibility. Rather than measuring "
        "absolute frequency alone, SOM evaluates a brand\u2019s share of total "
        "mentions relative to other brands within the same category and prompt "
        "set. This metric provides insight into how AI systems distribute "
        "attention across competitors, effectively revealing which brands "
        "dominate the recommendation layer and which are marginalized or "
        "excluded. SOM is particularly valuable because AI outputs often compress "
        "choice into a limited set of options, making relative share more "
        "meaningful than absolute presence. As such, SOM begins to approximate "
        "competitive strength within the AI-mediated layer, serving as a bridge "
        "between descriptive measurement and strategic interpretation."
    ),
}

# 5. SIX COMPONENTS OF AIAS
COMPONENTS = {
    "intro": {
        "short": "Six dimensions of AI-mediated visibility.",
        "medium": (
            "AIAS is composed of six components that together provide a more "
            "complete picture of brand performance within AI systems. These "
            "components move from basic visibility to deeper evaluation."
        ),
        "long": (
            "The AIAS system is composed of six interrelated components, each "
            "capturing a distinct dimension of how brands appear, compete, and "
            "are represented within AI-generated outputs. Together, these "
            "components form a multi-dimensional view of AI-mediated visibility, "
            "moving from basic presence to more nuanced assessments of position, "
            "stability, breadth, and accuracy. This modular structure allows the "
            "system to evolve over time, with each component adding incremental "
            "explanatory power. While early implementations may rely more "
            "heavily on foundational metrics such as Presence and SOM, the full "
            "system is designed to integrate all six components into a "
            "comprehensive framework capable of supporting strategic analysis "
            "and, eventually, decision-making."
        ),
    },
    "presence": {
        "short": "Are you visible?",
        "long": (
            "The Presence component measures how frequently a brand appears in "
            "AI-generated outputs. It represents the baseline condition for "
            "participation in AI-mediated competition and serves as the "
            "foundation for all other components."
        ),
    },
    "som": {
        "short": "Are you competitive?",
        "long": (
            "SOM evaluates a brand\u2019s share of total mentions relative to "
            "competitors. It reflects how AI systems allocate attention across "
            "brands within a category."
        ),
    },
    "ranking": {
        "short": "Where do you appear?",
        "long": (
            "Ranking captures the position of a brand within AI responses, "
            "recognizing that earlier mentions often carry more weight in "
            "shaping decisions."
        ),
    },
    "consistency": {
        "short": "Are you reliable?",
        "long": (
            "Consistency measures the stability of brand presence across models, "
            "prompts, and repeated runs, indicating how predictable a brand\u2019s "
            "visibility is."
        ),
    },
    "coverage": {
        "short": "Where do you show up?",
        "long": (
            "Coverage assesses the breadth of contexts in which a brand appears, "
            "reflecting its relevance across different use cases and prompts."
        ),
    },
    "grounding": {
        "short": "Are you accurate?",
        "long": (
            "Grounding evaluates whether brand mentions are correct, relevant, "
            "and aligned with actual product attributes and positioning."
        ),
    },
}

# 6. RESPONSE MODES
RESPONSE_MODES = {
    "short": "AI responds in different modes.",
    "medium": (
        "AI systems can respond in different ways depending on the query. "
        "Understanding these modes is essential."
    ),
    "long": (
        "AI systems do not consistently respond by recommending brands. Instead, "
        "they operate across multiple response modes depending on the structure "
        "of the query and the underlying training data. In Brand Mode, the system "
        "explicitly recommends or lists brands. In Component Mode, it focuses on "
        "features, specifications, or attributes without referencing brands. In "
        "Authority Mode, it provides generalized advice or expert-like guidance. "
        "This distinction is critical for interpreting AIAS metrics, as the "
        "absence of brand mentions does not necessarily imply absence of "
        "influence. A category dominated by component or authority responses may "
        "still be highly competitive, but at a different level of abstraction. "
        "Understanding these modes allows for more accurate interpretation of "
        "visibility and strategic positioning."
    ),
}

# 7. REPORT TYPES
REPORT_TYPES = {
    "short": "Different outputs for different uses.",
    "medium": (
        "The system produces different types of reports depending on scope. "
        "This structure allows flexibility."
    ),
    "long": (
        "The Third System framework is operationalized through a set of "
        "structured report types designed to address different analytical needs. "
        "Cross-category reports identify broad patterns and structural dynamics "
        "across industries. Category Intelligence reports provide deep analysis "
        "within a single domain, establishing benchmarks and competitive "
        "dynamics. Brand Visibility Diagnostics focus on individual companies, "
        "translating system-level insights into company-specific implications. "
        "Together, these report types enable the same underlying system to "
        "support research, strategic analysis, and commercial application, "
        "ensuring consistency while allowing flexibility in scope and depth."
    ),
}

# 8. VERSIONING
VERSIONING = {
    "short": "Tracks maturity.",
    "medium": (
        "Versioning indicates development stage. It helps communicate confidence."
    ),
    "long": (
        "Versioning is a critical component of the AIAS system, reflecting its "
        "iterative development and evolving reliability. Early versions (v0.X) "
        "represent exploratory stages where methodologies are still being "
        "refined and findings should be interpreted directionally. Version 1.0 "
        "marks the transition to a stable, repeatable system with consistent "
        "outputs. Subsequent versions (v1.X and beyond) introduce incremental "
        "improvements, additional components, and increased robustness. This "
        "structure ensures transparency in how the system evolves and provides "
        "users with a clear signal of confidence and maturity at each stage."
    ),
}

# 9. CORE STATEMENT
CORE_STATEMENT = {
    "short": "Simple system philosophy.",
    "medium": (
        "The system is designed around simplicity and consistency. It focuses "
        "on clarity."
    ),
    "long": (
        "The Third System and AIAS framework are built on a simple but powerful "
        "principle: one system, a small number of core metrics, and multiple "
        "applications. By limiting complexity at the metric level and "
        "maintaining consistency in language and structure, the system achieves "
        "clarity and scalability. This approach allows it to be applied across "
        "different contexts\u2014from academic research to executive "
        "decision-making\u2014without losing coherence. Over time, this simplicity "
        "becomes a source of strength, enabling widespread understanding, "
        "adoption, and extension of the framework."
    ),
}
